# Generated by Django 5.2.17 on 2026-09-14 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('competition', 'Competition'), ('team', 'Team')], default='personal', max_length=15)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(max_length=255)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
