# Generated by Django 5.2.17 on 2026-09-19 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 19, 15, 26, 30, 898442, tzinfo=datetime.timezone.utc)),
        ),
    ]
